name: Unit Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_call:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - target: iosSimulatorArm64Test
            os: macos-latest
          - target: jvmTest
            os: ubuntu-latest
          - target: testAndroidHostTest
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-java

      - name: run tests
        env:
          INCLUDE_SAMPLE: false
        run: |
          chmod +x gradlew
          ./gradlew ${{ matrix.target }}

  build-and-verify:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: ./.github/actions/setup-java
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run assembleDebug
        env:
          INCLUDE_SAMPLE: true
        run: |
          ./gradlew :processor:publishToMavenLocal :core:publishToMavenLocal :plugin:publishToMavenLocal
          ./gradlew :sample:assembleDebug
      - name: Verify generated file exists
        run: ls sample/build/generated/ksp/debug/kotlin/io/github/arashiyama11/composemark/sample/ContentsImpl.kt

